tap 'github/bootstrap'

# Useful utilities
brew 'ack'
brew 'autoconf'
brew 'automake'
brew 'bash-completion'
brew 'coreutils'
brew 'curl'
brew 'findutils'
brew 'gcc'
brew 'git'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'hub'
brew 'jq'
brew 'libxslt'
brew 'libyaml'
brew 'openssl'
brew 'pkg-config'
brew 'readline'
brew 'unixodbc'
brew 'zlib'

# Language runtime managers
brew 'asdf'

# Resolve *.localhost
brew "launchdns", restart_service: true
