name: Crystal CI

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install crystal
      run: brew install crystal-lang
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
