name: Tests

on:
  push:
    paths-ignore:
    - 'Dockerfile'
    - 'docs/**'
    - '*.hcl'
    - '*.md'
    - '*.yml'

jobs:
  macos-tests:
    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install crystal and tool dependencies
      run: brew install crystal meson

    - name: Install dependencies
      run: shards install

    - name: Run tests
      run: make test STATIC=1
      env:
        PKG_CONFIG_PATH: "/usr/local/opt/openssl@3/lib/pkgconfig"

  ubuntu-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Add Crystal repos
      run: curl -sSL https://crystal-lang.org/install.sh | sudo bash

    - name: Install crystal and tool dependencies
      run: |
        sudo apt install -y crystal libevent-dev libpcre3-dev libssl-dev ninja-build
        sudo apt purge meson
        sudo pip3 install meson

    - name: Install dependencies
      run: shards install

    - name: Run tests
      run: make test
