name: Tests

on:
  push:
    paths-ignore:
    - 'docs/**'
    - '*.hcl'
    - '*.md'
    - '*.yml'

jobs:
  macos-tests:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Homebrew to install from API
      run: echo HOMEBREW_NO_INSTALL_FROM_API= >> "$GITHUB_ENV"

    - name: Install crystal and tool dependencies
      run: brew install crystal meson openssl@3

    - name: Install dependencies
      run: shards install

    - name: Run lint
      run: make lint

    - name: Run tests
      run: make test STATIC=1

  ubuntu-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Add Crystal repos
      run: curl -sSL https://crystal-lang.org/install.sh | sudo bash

    - name: Install crystal and tool dependencies
      run: |
        sudo apt install -y crystal libevent-dev libpcre2-dev libssl-dev ninja-build
        sudo apt purge meson
        sudo pip3 install meson

    - name: Install dependencies
      run: shards install

    - name: Run lint
      run: make lint

    - name: Run tests
      run: make test
