name: Tests

on:
  push:
    paths-ignore:
    - 'docs/**'
    - '*.md'

jobs:
  tests:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install crystal
      run: brew install crystal-lang
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: make test
