name: Test Provisioning

# Provisioning tests are expensive, so we should only run them on master merges
# (until later determined to be insufficent)
on:
  push:
    branches:
    - master
    paths-ignore:
    - 'Dockerfile'
    - 'docs/**'
    - '*.hcl'
    - '*.md'

jobs:
  macos-provision:
    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install crystal
      run: brew install crystal

    - name: Install dependencies
      run: shards install

    - name: Build mstrap
      run: make build

    # Based on https://raw.githubusercontent.com/MikeMcQuaid/strap/master/.github/workflows/tests.yml

    - name: Run brew bot's cleanup
      run: brew test-bot --only-cleanup-before

    - name: Make macOS like new
      run: |
        sudo rm -rf /usr/local/bin/brew /usr/local/.??* \
                    /usr/local/Homebrew /usr/local/Caskroom \
                    /Library/Developer/CommandLineTools

    - name: Run initial mstrap process
      env:
        STRAP_CI: true
      run: |
        bin/mstrap --debug \
        --config ${{ secrets.TEST_CONFIG_URL }}

    - name: Finish mstrap process
      env:
        STRAP_CI: true
      run: |
        source ~/.mstrap/env.sh && bin/mstrap --debug

    - name: Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.1

    - name: Run serverspecs
      env:
        BUNDLE_DEPLOYMENT: true
      run: |
        source ~/.mstrap/env.sh && make check-provisioning

  ubuntu-provision:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Add Crystal repos
      run: curl -sSL https://dist.crystal-lang.org/apt/setup.sh | sudo bash

    - name: Install crystal
      run: |
        sudo apt install -y crystal libevent-dev libpcre3-dev libreadline-dev libssl-dev \
          curl \
          ruby ruby-bundler

    - name: Install dependencies
      run: shards install

    - name: Build mstrap
      run: make build

    - name: Make Ubuntu like new
      run: |
        sudo apt remove --purge build-essential git file
        sudo apt install curl

    - name: Run initial mstrap process
      env:
        SHELL: /bin/bash
        STRAP_CI: true
      run: |
        bin/mstrap --debug \
        --config ${{ secrets.TEST_CONFIG_URL }}

    - name: Finish mstrap process
      env:
        SHELL: /bin/bash
        STRAP_CI: true
      run: |
        source ~/.mstrap/env.sh && bin/mstrap --debug

    - name: Run serverspecs
      env:
        SHELL: /bin/bash
        BUNDLE_DEPLOYMENT: true
      run: |
        source ~/.mstrap/env.sh && make check-provisioning
